version: '3.8'

services:
  api:
    build: .
    container_name: webscraper-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DATABASE_URL=sqlite:///./webscraper.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["python", "-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  dashboard:
    build: .
    container_name: webscraper-dashboard
    ports:
      - "8501:8501"
    environment:
      - DASHBOARD_HOST=0.0.0.0
      - DASHBOARD_PORT=8501
      - API_BASE_URL=http://api:8000/api/v1
    depends_on:
      - api
    command: ["streamlit", "run", "src/dashboard/main.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    container_name: webscraper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
      - dashboard
    restart: unless-stopped

volumes:
  data:
  logs: